### ISSUE TITLE
Estudos das APIs

### ISSUE THREAD

**Issue by arthursgonzaga** [data-pandawans/DeathStarLake#4]
https://swapi.dev/

**Comment by Vinicius-Nassif** [comment]
<html>
<body>
<h2 id="Endpoints:" style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1; color: rgb(0, 0, 0); margin: 0.636em 0px 0px; font-size: 21.994px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Endpoints:<a class="anchor-link" href="http://localhost:8888/notebooks/Documents/Untitled.ipynb?kernel_name=python3#Endpoints:" style="box-sizing: border-box; background-color: transparent; color: rgb(41, 110, 170); text-decoration: none; padding: 0px 20px; visibility: hidden;"></a></h2><ul style="box-sizing: border-box; margin-top: 1em; margin-bottom: 9px; list-style: disc; padding-left: 2em; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: monospace; font-size: 14px; padding: 2px 4px; color: rgb(0, 0, 0); background-color: rgb(239, 240, 241); border-radius: 2px; white-space: pre-wrap; border: 0px;">/people</code>: Retorna informações sobre os personagens da saga Star Wars.</li><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: monospace; font-size: 14px; padding: 2px 4px; color: rgb(0, 0, 0); background-color: rgb(239, 240, 241); border-radius: 2px; white-space: pre-wrap; border: 0px;">/planets</code>: Retorna informações sobre os planetas presentes na saga Star Wars</li><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: monospace; font-size: 14px; padding: 2px 4px; color: rgb(0, 0, 0); background-color: rgb(239, 240, 241); border-radius: 2px; white-space: pre-wrap; border: 0px;">/films</code>: Retorna informações sobre os filmes da saga Star Wars.</li><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: monospace; font-size: 14px; padding: 2px 4px; color: rgb(0, 0, 0); background-color: rgb(239, 240, 241); border-radius: 2px; white-space: pre-wrap; border: 0px;">/starships</code>: Retorna informações sobre as naves espaciais presentes na saga Star Wars.</li><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: monospace; font-size: 14px; padding: 2px 4px; color: rgb(0, 0, 0); background-color: rgb(239, 240, 241); border-radius: 2px; white-space: pre-wrap; border: 0px;">/vehicles</code>: Retorna informações sobre os veículos presentes na saga Star Wars.</li><li style="box-sizing: border-box;"><code style="box-sizing: border-box; font-family: monospace; font-size: 14px; padding: 2px 4px; color: rgb(0, 0, 0); background-color: rgb(239, 240, 241); border-radius: 2px; white-space: pre-wrap; border: 0px;">/species</code>: Retorna informações sobre as espécies presentes na saga Star Wars.</li></ul><h2 id="Estrutura-dos-dados:" style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1; color: rgb(0, 0, 0); margin: 1.27em 0px 0px; font-size: 21.994px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Estrutura dos dados:<a class="anchor-link" href="http://localhost:8888/notebooks/Documents/Untitled.ipynb?kernel_name=python3#Estrutura-dos-dados:" style="box-sizing: border-box; background-color: transparent; color: rgb(41, 110, 170); text-decoration: none; padding: 0px 20px; visibility: hidden;"></a></h2><ul style="box-sizing: border-box; margin-top: 1em; margin-bottom: 9px; list-style: disc; padding-left: 2em; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0px; text-align: left;">Cada recurso na API, como pessoas (people), planetas (planets), filmes (films), naves espaciais (starships), veículos (vehicles) e espécies (species), segue uma estrutura de dados semelhante.</p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0px; text-align: left;">Os dados são retornados no formato JSON (JavaScript Object Notation).</p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0px; text-align: left;">Cada recurso possui diversos atributos que fornecem informações específicas sobre ele.</p>

Endpoints | Atributos retornados | Nome das colunas
-- | -- | --
"/people" (Personagens) | name, birth_year, eye_color, gender, hair_color, height, mass, skin_color, homeworld, films, species, starships, vehicles, url, created, edited | Nome, Ano de Nascimento, Cor dos Olhos, Gênero, Cor do Cabelo, Altura, Peso, Cor da Pele, Planeta Natal, Filmes, Espécies, Naves Espaciais, Veículos, URL, Criado, Editado
"/planets" (Planetas) | name, diameter, rotation_period, orbital_period, gravity, population, climate, terrain, surface_water, residents, films, url, created, edited | Nome, Diâmetro, Período de Rotação, Período Orbital, Gravidade, População, Clima, Terreno, Água na Superfície, Residentes, Filmes, URL, Criado, Editado
"/films" (Filmes) | title, episode_id, opening_crawl, director, producer, release_date, characters, planets, starships, vehicles, species, url, created, edited | Título, Número do Episódio, Texto de Abertura, Diretor, Produtor, Data de Lançamento, Personagens, Planetas, Naves Espaciais, Veículos, Espécies, URL, Criado, Editado
"/starships" (Naves espaciais) | name, model, manufacturer, cost_in_credits, length, max_atmosphering_speed, crew, passengers, cargo_capacity, consumables, hyperdrive_rating, MGLT, starship_class, pilots, films, url, created, edited | Nome, Modelo, Fabricante, Custo em Créditos, Comprimento, Velocidade Máxima na Atmosfera, Tripulação, Passageiros, Capacidade de Carga, Consumíveis, Classificação do Hiperdrive, Megalights, Classe da Nave Espacial, Pilotos, Filmes, URL, Criado, Editado
"/vehicles" (Veículos) | name, model, manufacturer, cost_in_credits, length, max_atmosphering_speed, crew, passengers, cargo_capacity, consumables, vehicle_class, pilots, films, url, created, edited | Nome, Modelo, Fabricante, Custo em Créditos, Comprimento, Velocidade Máxima na Atmosfera, Tripulação, Passageiros, Capacidade de Carga, Consumíveis, Classe do Veículo, Pilotos, Filmes, URL, Criado, Editado
"/species" (Espécies) | name, classification, designation, average_height, average_lifespan, eye_colors, hair_colors, skin_colors, language, homeworld, people, films, url, created, edited | Nome, Classificação, Designação, Altura Média, Expectativa de Vida Média, Cores dos Olhos, Cores do Cabelo, Cores da Pele, Idioma, Planeta Natal, Personagens, Filmes, URL, Criado, Editado

</li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0px; text-align: left;">Alguns atributos, como "films" e "homeworld", são representados como URLs que podem ser seguidas para obter informações detalhadas sobre outros recursos relacionados.</p></li></ul>
</body>
</html>

<html>
<body>
<h2 id="Relacionamentos:" style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1; color: rgb(0, 0, 0); margin: 1.27em 0px 0px; font-size: 21.994px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Relacionamentos:<a class="anchor-link" href="http://localhost:8888/notebooks/Documents/Untitled.ipynb?kernel_name=python3#Relacionamentos:" style="box-sizing: border-box; background-color: transparent; color: rgb(41, 110, 170); text-decoration: none; padding: 0px 20px; visibility: hidden;"></a></h2><ul style="box-sizing: border-box; margin-top: 1em; margin-bottom: 9px; list-style: disc; padding-left: 2em; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;">A SWAPI possui relacionamentos entre os recursos, permitindo que você navegue entre eles e obtenha informações relacionadas.</li><li style="box-sizing: border-box;">Por exemplo, ao acessar as informações de um personagem (people), você encontrará um campo "films" que contém uma lista de URLs que representam os filmes em que o personagem aparece. Você pode seguir essas URLs para obter mais informações sobre os filmes relacionados.</li><li style="box-sizing: border-box;">Você pode seguir esses URLs para obter informações detalhadas sobre cada filme, como título, diretor, data de lançamento, personagens associados, entre outros atributos.</li><li style="box-sizing: border-box;">Além disso, os recursos também podem ter campos relacionados a outros recursos, como "homeworld" (representando o planeta natal de um personagem e suas informações detalhadas) ou "starships" (representando as naves espaciais associadas a um filme).</li><li style="box-sizing: border-box;">Aqui está uma tabela que apresenta os detalhes de relacionamento de cada recurso.</li></ul>

Recurso | Atributo de relacionamento | Descrição
-- | -- | --
People | homeworld | URL do planeta natal do personagem
  | films | Lista de URLs dos filmes em que o personagem aparece
  | species | Lista de URLs das espécies às quais o personagem pertence
  | starships | Lista de URLs das naves espaciais associadas ao personagem
  | vehicles | Lista de URLs dos veículos associados ao personagem
Planets | residents | Lista de URLs dos personagens que residem no planeta
  | films | Lista de URLs dos filmes em que o planeta aparece
Films | characters | Lista de URLs dos personagens presentes no filme
  | planets | Lista de URLs dos planetas presentes no filme
  | starships | Lista de URLs das naves espaciais presentes no filme
  | vehicles | Lista de URLs dos veículos presentes no filme
  | species | Lista de URLs das espécies presentes no filme
Starships | pilots | Lista de URLs dos personagens que pilotaram a nave
  | films | Lista de URLs dos filmes em que a nave espacial aparece
Vehicles | pilots | Lista de URLs dos personagens que pilotaram o veículo
  | films | Lista de URLs dos filmes em que o veículo aparece
Species | homeworld | URL do planeta natal da espécie
  | people | Lista de URLs dos personagens que pertencem à espécie
  | films | Lista de URLs dos filmes em que a espécie aparece

<br class="Apple-interchange-newline">
</body>
</html>

## Autenticação:
A SWAPI não requer autenticação. Portanto, você pode fazer solicitações aos endpoints sem a necessidade de chaves de API ou tokens.

## Limites e diretrizes:
Não há limites de taxa especificados na documentação da SWAPI. No entanto, é sempre bom fazer solicitações responsáveis e respeitar as diretrizes de uso.

**Comment by Vinicius-Nassif** [comment]
# SWAPI
## Endpoints:

- `/people`: Retorna informações sobre os personagens da saga Star Wars.
- `/planets`: Retorna informações sobre os planetas presentes na saga Star Wars.
- `/films`: Retorna informações sobre os filmes da saga Star Wars.
- `/starships`: Retorna informações sobre as naves espaciais presentes na saga Star Wars.
- `/vehicles`: Retorna informações sobre os veículos presentes na saga Star Wars.
- `/species`: Retorna informações sobre as espécies presentes na saga Star Wars.

## Estrutura dos dados:

- Cada recurso na API, como pessoas (people), planetas (planets), filmes (films), naves espaciais (starships), veículos (vehicles) e espécies (species), segue uma estrutura de dados semelhante.

- Os dados são retornados no formato JSON (JavaScript Object Notation).

- Cada recurso possui diversos atributos que fornecem informações específicas sobre ele.

| Endpoints                      | Atributos retornados                                         | Nome das colunas                                             |
| ------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| "/people" (Personagens)        | name, birth_year, eye_color, gender, hair_color, height, mass, skin_color, homeworld, films, species, starships, vehicles, url, created, edited | Nome, Ano de Nascimento, Cor dos Olhos, Gênero, Cor do Cabelo, Altura, Peso, Cor da Pele, Planeta Natal, Filmes, Espécies, Naves Espaciais, Veículos, URL, Criado, Editado |
| "/planets" (Planetas)          | name, diameter, rotation_period, orbital_period, gravity, population, climate, terrain, surface_water, residents, films, url, created, edited | Nome, Diâmetro, Período de Rotação, Período Orbital, Gravidade, População, Clima, Terreno, Água na Superfície, Residentes, Filmes, URL, Criado, Editado |
| "/films" (Filmes)              | title, episode_id, opening_crawl, director, producer, release_date, characters, planets, starships, vehicles, species, url, created, edited | Título, Número do Episódio, Texto de Abertura, Diretor, Produtor, Data de Lançamento, Personagens, Planetas, Naves Espaciais, Veículos, Espécies, URL, Criado, Editado |
| "/starships" (Naves espaciais) | name, model, manufacturer, cost_in_credits, length, max_atmosphering_speed, crew, passengers, cargo_capacity, consumables, hyperdrive_rating, MGLT, starship_class, pilots, films, url, created, edited | Nome, Modelo, Fabricante, Custo em Créditos, Comprimento, Velocidade Máxima na Atmosfera, Tripulação, Passageiros, Capacidade de Carga, Consumíveis, Classificação do Hiperdrive, Megalights, Classe da Nave Espacial, Pilotos, Filmes, URL, Criado, Editado |
| "/vehicles" (Veículos)         | name, model, manufacturer, cost_in_credits, length, max_atmosphering_speed, crew, passengers, cargo_capacity, consumables, vehicle_class, pilots, films, url, created, edited | Nome, Modelo, Fabricante, Custo em Créditos, Comprimento, Velocidade Máxima na Atmosfera, Tripulação, Passageiros, Capacidade de Carga, Consumíveis, Classe do Veículo, Pilotos, Filmes, URL, Criado, Editado |
| "/species" (Espécies)          | name, classification, designation, average_height, average_lifespan, eye_colors, hair_colors, skin_colors, language, homeworld, people, films, url, created, edited | Nome, Classificação, Designação, Altura Média, Expectativa de Vida Média, Cores dos Olhos, Cores do Cabelo, Cores da Pele, Idioma, Planeta Natal, Personagens, Filmes, URL, Criado, Editado |

- Alguns atributos, como "films" e "homeworld", são representados como URLs que podem ser seguidas para obter informações detalhadas sobre outros recursos relacionados.

## Relacionamentos: 

- A SWAPI possui relacionamentos entre os recursos, permitindo a navegação entre eles e obtenha informações relacionadas.
- Por exemplo, ao acessar as informações de um personagem (people),  será encontrado um campo "films" que contém uma lista de URLs que representam os filmes em que o personagem aparece. Pode-se seguir essas URLs para obter mais informações sobre os filmes relacionados.
- Pode-se seguir esses URLs para obter informações detalhadas sobre cada filme, como título, diretor, data de lançamento, personagens associados, entre outros atributos.
- Além disso, os recursos também podem ter campos relacionados a outros recursos, como "homeworld" (representando o planeta natal de um personagem e suas informações detalhadas) ou "starships" (representando as naves espaciais associadas a um filme).

Aqui está uma tabela que apresenta os detalhes de relacionamento de cada recurso.

| Recurso   | Atributo de relacionamento | Descrição                                                  |
| --------- | -------------------------- | ---------------------------------------------------------- |
| People    | homeworld                  | URL do planeta natal do personagem                         |
|           | films                      | Lista de URLs dos filmes em que o personagem aparece       |
|           | species                    | Lista de URLs das espécies às quais o personagem pertence   |
|           | starships                  | Lista de URLs das naves espaciais associadas ao personagem |
|           | vehicles                   | Lista de URLs dos veículos associados ao personagem        |
| Planets   | residents                  | Lista de URLs dos personagens que residem no planeta       |
|           | films                      | Lista de URLs dos filmes em que o planeta aparece          |
| Films     | characters                 | Lista de URLs dos personagens presentes no filme           |
|           | planets                    | Lista de URLs dos planetas presentes no filme              |
|           | starships                  | Lista de URLs das naves espaciais presentes no filme       |
|           | vehicles                   | Lista de URLs dos veículos presentes no filme              |
|           | species                    | Lista de URLs das espécies presentes no filme              |
| Starships | pilots                     | Lista de URLs dos personagens que pilotaram a nave         |
|           | films                      | Lista de URLs dos filmes em que a nave espacial aparece    |
| Vehicles  | pilots                     | Lista de URLs dos personagens que pilotaram o veículo      |
|           | films                      | Lista de URLs dos filmes em que o veículo aparece          |
| Species   | homeworld                  | URL do planeta natal da espécie                            |
|           | people                     | Lista de URLs dos personagens que pertencem à espécie      |
|           | films                      | Lista de URLs dos filmes em que a espécie aparece          |

## Paginação:
O sistema de paginação da API segue o padrão de paginação comumente utilizado em APIs RESTful. A páginação é usada para dividir grandes conjuntos de dados em páginas menores, facilitando a recuperação e visualização desses dados em partes.

A API usa a paginação baseada em cursor, onde o cliente especifica um ponto de referência (um cursor) para obter a próxima página de resultados. O cursor é fornecido na resposta da API como um campo chamado "next" que contém a URL para a próxima página.

Por exemplo, ao fazer uma chamada para a API para obter a lista de filmes, você receberá uma resposta JSON com os resultados e um campo "next" contendo a URL para a próxima página. Se você quiser obter os resultados da próxima página, basta fazer uma nova solicitação GET para a URL fornecida em "next".

## Autenticação:

A SWAPI não requer autenticação. Portanto, é possível fazer solicitações aos endpoints sem a necessidade de chaves de API ou tokens.

## Limites e diretrizes:

Não há limites de taxa especificados na documentação da SWAPI. No entanto, é sempre bom fazer solicitações responsáveis e respeitar as diretrizes de uso.

**Comment by arthursgonzaga** [comment]
Vini, acho que vale colocarmos essas informações na Wiki. O que acha?

**Comment by arthursgonzaga** [comment]
Próximos passos:

- Localmente instalar o ambiente para desenvolvimento (Tutis);
- Capturar informações dos 6 endpoints (Alex + Nassif):
  - Usar lib `requests` para realizar a captura das informações
  - Salvar as informações pasta local (dentro do nosso repositório)
