### ISSUE TITLE
Desenvolvimento das primeiras extrações

### ISSUE THREAD

**Issue by arthursgonzaga** [data-pandawans/DeathStarLake#8]

**Comment by AllexRocha** [comment]
Olá pessoal irei ficar responsável por essas duas se não se importarem:

/people: Retorna informações sobre os personagens da saga Star Wars.
/planets: Retorna informações sobre os planetas presentes na saga Star Wars.

**Comment by Vinicius-Nassif** [comment]
Olá, pessoal! Realizei a extração dos endpoints abaixo e armazenei em um .csv

/films: Retorna informações sobre os filmes da saga Star Wars.
/starships: Retorna informações sobre as naves espaciais presentes na saga Star Wars.

**Comment by dgeison** [comment]
Fiquei com a extração dos veículos e especies:
/vehicles: Retorna informações sobre os veículos presentes na saga Star Wars.
/species: Retorna informações sobre as espécies presentes na saga Star Wars.

Já concluí e vou subir em uma branch nova, correto?

**Comment by arthursgonzaga** [comment]
Positivo, Dgeison!!
